# Generated by Django 4.2.1 on 2023-05-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchdata',
            name='brand',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='watchdata',
            name='model',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='watchdata',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='watchdata',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='watchdata',
            name='user_name',
            field=models.CharField(max_length=255),
        ),
    ]
