# Generated by Django 4.2.1 on 2023-05-29 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_alter_watchdata_brand_alter_watchdata_model_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchdata',
            options={'verbose_name_plural': 'Watch Data'},
        ),
    ]
