# Generated by Django 4.2.1 on 2023-05-30 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchdata',
            options={},
        ),
        migrations.AddField(
            model_name='watchdata',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='watchlist.category'),
        ),
        migrations.AddField(
            model_name='watchdata',
            name='price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='watchdata',
            name='model',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
